spring.application.name=Arena-Connect

spring.datasource.url=jdbc:postgresql://localhost:5432/arenaconnect
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate - Configuracao SIMPLES
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.multiTenancy=SCHEMA

# JWT
jwt.secret=${JWT_SECRET}
jwt.expiration=86400000
server.port=8080

# Logging
logging.level.com.example.Multitenancy=DEBUG
logging.level.org.hibernate.SQL=DEBUG

# Asaas API Configuration
asaas.api.url=https://sandbox.asaas.com/api/v3
asaas.api.key=${ASAAS_API_KEY}
asaas.master.wallet.id=${ASAAS_MASTER_WALLET_ID}
asaas.webhook.auth-token=${ASAAS_WEBHOOK_AUTH_TOKEN:}

#google id de cliente
google.client.id=${GOOGLE_CLIENT_ID}

#config google email sender
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${SPRING_MAIL_USERNAME}
spring.mail.password=${SPRING_MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# groq API Key
groq.api.key=${GROQ_API_KEY}

# para criar o superadmin assim que rodar o sistema
spring.sql.init.mode=always
spring.sql.init.data-locations=classpath:sql/data.sql
spring.jpa.defer-datasource-initialization=true
